version: "3"
services:
  postgres:
      image: library/postgres:13
      container_name: postgres
      restart: on-failure
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: "postgres"
        POSTGRES_DB: postgres
      volumes:
        - db-data:/var/lib/postgresql/data
        - ./postgres/:/docker-entrypoint-initdb.d/
      ports:
        - "5432:5432"

  cars_service:
    build: src/cars_service
    container_name: cars_service
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8070:8070"

  payment_service:
    build: src/payment_service
    container_name: payment_service
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8050:8050"

  rental_service:
    build: src/rental_service
    container_name: rental_service
    environment:
      DATA_BASE_PORT: "5432"
      DATA_BASE_NAME: "postgres"
      DATA_BASE_USER: "postgres"
      DATA_BASE_PASS: "postgres"
      DATA_BASE_HOST: "postgres"
    ports:
      - "8060:8060"

  gate_way_service:
    build: src/gate_way_service
    container_name: gate_way_service
    environment:
      CARS_SERVICE_HOST: "cars_service"
      CARS_SERVICE_PORT: "8070"
      PAYMENT_SERVICE_HOST: "payment_service"
      PAYMENT_SERVICE_PORT: "8050"
      RENTAL_SERVICE_HOST: "rental_service"
      RENTAL_SERVICE_PORT: "8060"
      QUEUE_SERVICE_HOST: "queue_service"
      QUEUE_SERVICE_PORT: "8040"
    ports:
      - "8080:8080"

  queue_service:
    build: src/queue_service
    container_name: queue_service
    ports:
      - "8040:8040"
volumes:
  db-data: